### ISSUE TITLE
Signing seems broken. No pop up UI in MetaMask and AlphaWallet to approve signing

### ISSUE THREAD

**Issue by hboon** [James-Sangalli/xcontract#5]
Signing seems broken. No pop up UI in MetaMask and AlphaWallet to approve signing
URL: https://xcontract.herokuapp.com/sign

With MetaMask, this appears in logs:

> injected provider used: [object Object]
> bundle.js:55137 Here is the account: undefined
> bundle.js:55139 message to sign: hello
> bundle.js:55379 signing error: TypeError: Cannot read property 'length' of undefined

[Privacy Mode for MetaMask](#6) is off. Doesn't work for both the current version of MetaMask and the older version before Privacy Mode was introduced.

**Comment by James-Sangalli** [comment]
Works here on AlphaWallet: 0b1671ca6a63e5a67ce09d93df2a480c57aebc35 

Latest metamask treats the message like ascii hex and fails to sign it
